require "user.options"
require "user.keymaps"
require "user.plugins"
-- require "user.colorscheme"
-- require "user.lsp
-- require "user.jeff-lsp"
require "completion"
require "lsp"
require "treesitter"
require "autopairs"
require "_gitsigns"

-- require "jerf.bufferline"
require "jerf.smoothscroll"
require "jerf.toggle-term"
require "jerf.comment"
require "jerf.telescope"
require "jerf.nvimtree"
require "jerf.barbar"
require "jerf.colors"

require "globals"
