vim.g.mapleader = " "
vim.opt.updatetime = 300
vim.opt.number = true
vim.opt.relativenumber = false
-- vim.opt.showtabline = 2 
vim.opt.tabstop = 2
vim.opt.shiftwidth = 2
vim.opt.cursorline = true
vim.opt.smartindent = true
vim.opt.expandtab = true
vim.opt.clipboard = "unnamedplus"
